language: C
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
os:
  - linux
  - osx
sudo: required
env:
  global:
    - DEPS_DIR="${HOME}/deps"
    - COVERAGE="true"
    - PYTHON_VERSION="3.5"
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
after_success: bash ci/travis/coverage.sh
branches:
  only:
  - master
  - continuous_integration
