language: C

os:
  - linux
  - osx
sudo: required
env:
  global:
    - DEPS_DIR="${HOME}/deps"
    - COVERAGE="true"
    - secure: "f4awzp9VOACVLsU3myJTA6FjY41oRtojpORJL5vIRQMNj4IMEMOvEOzuFY4/yK0msUK/mbQwY3JZys/uA0aWWMVy3J6Sq5jZO4uWtyhrEjaccF8xTtH4S1p53QzSIHUoddZl9fbDbtWrWjMYV4o31yZjtGWGgpZpyS/dnLshqiduJgiddbfY5+W1YXGOCopu5JUYgBpgmL+vwNGxSWpiO8TwT+av2xjbYMIENYtr3bMZhBTk6D9cvZvrKedKULyMDBOC0vkMsd33UNkP+oCYkSLqes2syeQNsbYD9+EXRhCmJugUtdMI0UXB/49wVoy23CEggHFmgHKJpd/ZCE1Gd6CJZ5ZPi+1SPvnUja45dryLV44rk6jg+t4V5XF7/D+89wYp7d83roOgtfj2s91oFYhLn5OrghO7y5H0gjhgcCWVJkqQBRtAyorzF0ByWMTe1QN8Br7rAiqbKjGRTyfJmSxOExqb1Y6CdDUJNUFptw5HUCnkJ1HpUolFpEXEBB2I4phCEeJhxqIlksNlMg/1oBr3r4sWrAi7uS8qyDB7vwDus8lH4HENDZCEQb/IiqHxeLWurxtSr9OCNnQCc0zNoPAjl+7iwX+TksuvBItGm6qJDq04mA6zDwcypQ9pr29joti0hv7NwdlUJNfsbDQzGjgT76EJ7CLX7IB76k6cQwE="
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
branches:
  only:
  - master
  - continuous_integration


deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: "sh $TRAVIS_BUILD_DIR/ci/travis/deploy.sh"
    on:
        branch: continuous_integration
    #   tags: true
    skip_cleanup: true
