language: C

os:
  - linux
  - osx
sudo: required
env:
  global:
    - DEPS_DIR="${HOME}/deps"
    - COVERAGE="true"
    - ANACONDA_TOKEN="ox-a17c699f-1776-436c-af24-74620852ae91%"
  matrix:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.4"
    - PYTHON_VERSION="3.5"
    - PYTHON_VERSION="3.6"
install: bash ci/travis/install.sh
script: bash ci/travis/script.sh
after_success: bash ci/travis/coverage.sh
branches:
  only:
  - master
  - continuous_integration


deploy:
 # Deploy to Anaconda.org
  - provider: script
    script: ci/travis/deploy_anaconda.sh
    # on:
    #   tags: true
    skip_cleanup: true
