# Not a .NET project. We build it in the install: script
build: false

platform:
    - x64
    - x86

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - %comspec% .\\ci\\appveyor\\install.cmd

test_script:
  - %comspec% .\\ci\\appveyor\\script.cmd
