# Not a .NET project. We build it in the install: script
build: false

platform:
  - x64
  - x86

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      CMAKE_PROJECT: MinGW Makefiles
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3
      CMAKE_PROJECT: MinGW Makefiles

branches:
  only:
    - continuous_integration

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%

install:
  - cmd .\\ci\\appveyor\\install.cmd

test_script:
  - cmd .\\ci\\appveyor\\script.cmd
